# Generated by Django 4.2.5 on 2023-09-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
