# Generated by Django 4.2.5 on 2023-09-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='description',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'USER'), (2, 'COUNSELOR'), (3, 'MODERATOR')], default=0),
        ),
    ]
