# Generated by Django 4.2.5 on 2023-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_counselor_description_counselor_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
