# Generated by Django 4.2.5 on 2023-09-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_otp_user_otp_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
